[package]
name = "gfx-scratchpad"
version = "0.1.0"
authors = ["Brent Houghton <brent@slixbits.com>"]

[dependencies]
cgmath = "0.12.*"
error-chain = "0.5.*"
gfx = "0.12.*"
glutin = "0.6.*"
gfx_window_glutin = "0.12.*"
gfx_device_gl = "0.11.*"
